name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      - name: Install Capacitor
        run: |
          npm install @capacitor/core
          npm install @capacitor/cli
          npm install @capacitor/android

      - name: Init Capacitor
        run: |
          npx cap init saasvala com.saasvala.app --web-dir=dist
          npx cap add android
          npx cap copy

      - name: Clean Gradle Cache
        run: rm -rf ~/.gradle/caches

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew assembleDebug --no-daemon --refresh-dependencies

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
